# Generated by Django 4.2.2 on 2023-06-22 21:54

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrency', models.CharField(max_length=3)),
                ('xprivate_key', django_cryptography.fields.encrypt(models.CharField(default=None, max_length=200))),
                ('xpublic_key', django_cryptography.fields.encrypt(models.CharField(default=None, max_length=200))),
                ('private_key', django_cryptography.fields.encrypt(models.CharField(default=None, max_length=200))),
                ('public_key', django_cryptography.fields.encrypt(models.CharField(default=None, max_length=200))),
                ('wif', django_cryptography.fields.encrypt(models.CharField(default=None, max_length=200))),
                ('finger_print', django_cryptography.fields.encrypt(models.CharField(default=None, max_length=200))),
                ('semantic', django_cryptography.fields.encrypt(models.CharField(default=None, max_length=200))),
                ('path', django_cryptography.fields.encrypt(models.CharField(default=None, max_length=200))),
                ('hash_data', django_cryptography.fields.encrypt(models.CharField(default=None, max_length=200))),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addreses', to='crypto_addresses.address')),
            ],
        ),
    ]
