# Generated by Django 4.2.2 on 2023-06-23 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='address',
        ),
        migrations.AddField(
            model_name='address',
            name='wallet',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='addreses', to='crypto_addresses.wallet'),
            preserve_default=False,
        ),
    ]
