# Generated by Django 4.2.2 on 2023-06-21 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_addresses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='cryptocurrency',
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptocurrency', models.CharField(max_length=3)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addreses', to='crypto_addresses.address')),
            ],
        ),
    ]
