# Generated by Django 4.2.2 on 2023-06-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_addresses', '0002_remove_wallet_address_address_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='crypto_addresses.wallet'),
        ),
    ]
